# Generated by Django 5.2.5 on 2025-08-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Общаг (Главная касса)',
                'verbose_name_plural': 'Общаг (Главная касса)',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('common_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='finances.commoncash')),
            ],
            options={
                'verbose_name': 'Движение денег',
                'verbose_name_plural': 'Движения денег',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Назначение')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.estimateitem', verbose_name='Позиция сметы')),
                ('common_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finances.commoncash')),
            ],
            options={
                'verbose_name': 'Выделение средств',
                'verbose_name_plural': 'Выделения средств',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.estimateitem')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь квартиры')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма продажи')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client_info', models.TextField(blank=True, verbose_name='Информация о клиенте')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='projects.block')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
