# Generated by Django 5.2.5 on 2025-08-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('projects', '0002_remove_block_sold_area_remove_block_total_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='estimate_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.estimateitem', verbose_name='Позиция сметы'),
        ),
    ]
