# Generated by Django 5.2.5 on 2025-09-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_allocation_estimate_item'),
        ('projects', '0013_alter_apartment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='projects.block'),
        ),
    ]
