# Generated by Django 5.2.5 on 2025-09-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_cashflow_block'),
        ('projects', '0013_alter_apartment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='common_cash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finances.commoncash'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='estimate_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.estimateitem', verbose_name='Позиция сметы'),
        ),
    ]
