# Generated by Django 5.2.5 on 2025-09-07 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_sale_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('given', 'Выданный займ'), ('taken', 'Полученный займ')], max_length=10, verbose_name='Тип займа')),
                ('contractor', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма займа')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Дата возврата')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процентная ставка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('repaid', 'Погашенный'), ('overdue', 'Просроченный')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='finances.commoncash')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Займ',
                'verbose_name_plural': 'Займы',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.loan')),
            ],
            options={
                'verbose_name': 'Платеж по займу',
                'verbose_name_plural': 'Платежи по займам',
            },
        ),
    ]
