# Generated by Django 5.2.5 on 2025-09-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_loan_loanpayment'),
        ('projects', '0014_apartmentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows12', to='projects.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='sale',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='projects.apartment', verbose_name='Квартира'),
        ),
    ]
