# Generated by Django 5.2.5 on 2025-09-23 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_cashflow_apartment_sale_apartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Марка/Модель')),
                ('vin_number', models.CharField(max_length=100, unique=True, verbose_name='VIN номер')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена покупки')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена продажи')),
                ('status', models.CharField(choices=[('available', 'В наличии'), ('sold', 'Продана')], default='available', max_length=20, verbose_name='Статус')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('sale_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('common_cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='finances.commoncash', verbose_name='Общаг')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Машина на складе',
                'verbose_name_plural': 'Машины на складе',
            },
        ),
    ]
