# Generated by Django 5.2.5 on 2026-01-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('sales', 'В продаже'), ('building', 'Строится'), ('design', 'Проект'), ('done', 'Сдан')], default='building', max_length=20)),
                ('name_ru', models.CharField(max_length=120)),
                ('name_ky', models.CharField(blank=True, max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('tagline_ru', models.CharField(blank=True, max_length=220)),
                ('tagline_ky', models.CharField(blank=True, max_length=220)),
                ('tagline_en', models.CharField(blank=True, max_length=220)),
                ('about_ru', models.TextField(blank=True)),
                ('about_ky', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True)),
                ('advantages_ru', models.TextField(blank=True)),
                ('advantages_ky', models.TextField(blank=True)),
                ('advantages_en', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='public_site/projects/hero/')),
                ('pdf', models.FileField(blank=True, upload_to='public_site/projects/pdfs/')),
                ('blocks_count', models.PositiveIntegerField(blank=True, null=True)),
                ('plot_area_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('apartments_count', models.PositiveIntegerField(blank=True, null=True)),
                ('underground_parking', models.PositiveIntegerField(blank=True, null=True)),
                ('guest_parking', models.PositiveIntegerField(blank=True, null=True)),
                ('building_density_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('has_smart_home', models.BooleanField(default=False)),
                ('has_boiler_house', models.BooleanField(default=False)),
                ('has_own_park', models.BooleanField(default=False)),
                ('has_lake', models.BooleanField(default=False)),
                ('sales_address_ru', models.CharField(blank=True, max_length=220)),
                ('sales_address_ky', models.CharField(blank=True, max_length=220)),
                ('sales_address_en', models.CharField(blank=True, max_length=220)),
                ('phones', models.CharField(blank=True, help_text='через запятую', max_length=200)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public_site/projects/gallery/')),
                ('title_ru', models.CharField(blank=True, max_length=120)),
                ('title_ky', models.CharField(blank=True, max_length=120)),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public_site.project')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('ab', 'A/Б'), ('v', 'В'), ('g', 'Г'), ('other', 'Другое')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='public_site/projects/plans/')),
                ('title_ru', models.CharField(blank=True, max_length=160)),
                ('title_ky', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='public_site.project')),
            ],
            options={
                'ordering': ['block', 'sort', 'id'],
            },
        ),
    ]
