# Generated by Django 5.2.5 on 2026-01-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_project_projectimage_projectplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=20, verbose_name='Блок')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Номер квартиры')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Комнат')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площадь (м²)')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('delivery_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок сдачи (год)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена ($)')),
                ('installment_from_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Рассрочка от ($/мес)')),
                ('installment_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рассрочка до (мес)')),
                ('status', models.CharField(choices=[('available', 'Свободна'), ('reserved', 'Бронь'), ('sold', 'Продана')], default='available', max_length=20, verbose_name='Статус')),
                ('kind', models.CharField(choices=[('living', 'Жилые'), ('commercial', 'Коммерческие')], default='living', max_length=20, verbose_name='Тип')),
                ('img_plan', models.ImageField(blank=True, upload_to='public_site/apartments/plan/', verbose_name='Планировка')),
                ('img_inside', models.ImageField(blank=True, upload_to='public_site/apartments/inside/', verbose_name='Фото квартиры')),
                ('img_top', models.ImageField(blank=True, upload_to='public_site/apartments/top/', verbose_name='Вид сверху')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='public_site.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['sort', '-id'],
            },
        ),
    ]
