# Generated by Django 5.2.5 on 2025-08-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название/Литер блока')),
                ('floors', models.IntegerField(verbose_name='Количество этажей')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая площадь блока')),
                ('sold_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Проданная площадь')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='EstimateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория сметы',
                'verbose_name_plural': 'Категории смет',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ЖК')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая площадь ЖК')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Объект (ЖК)',
                'verbose_name_plural': 'Объекты (ЖК)',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование материала/работы')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за единицу')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='projects.block')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.estimatecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции смет',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.project'),
        ),
    ]
