# Generated by Django 5.2.5 on 2025-08-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='sold_area',
        ),
        migrations.RemoveField(
            model_name='block',
            name='total_area',
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('apartment_number', models.CharField(max_length=20, verbose_name='Номер квартиры')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (m²)')),
                ('sold_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Проданная площадь (m²)')),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за m²')),
                ('deal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сделка')),
                ('deal_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер сделки')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО клиента')),
                ('remaining_deal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток от сделки')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Бронь')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('planned_price_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Планируемая цена m²')),
                ('planned_deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Планируемая сделка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='projects.block')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['block', 'floor', 'apartment_number'],
            },
        ),
        migrations.CreateModel(
            name='DealPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('payment_date', models.DateTimeField(verbose_name='Дата платежа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.apartment')),
            ],
            options={
                'verbose_name': 'Платеж по сделке',
                'verbose_name_plural': 'Платежи по сделкам',
                'ordering': ['-payment_date'],
            },
        ),
    ]
