# Generated by Django 5.2.5 on 2025-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_block_sold_area_remove_block_total_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сделка'),
        ),
    ]
