# Generated by Django 5.2.5 on 2025-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_apartment_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='remaining_deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Остаток от сделки'),
        ),
    ]
