# Generated by Django 5.2.5 on 2025-08-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_apartment_remaining_deal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deal_Fakt_deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена Сделки'),
        ),
    ]
