# Generated by Django 5.2.5 on 2025-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_apartment_deal_fakt_deal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='fact_price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Планируемая Цена за m²'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='fakt_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Планируемая Цена за m²'),
        ),
    ]
