# Generated by Django 5.2.5 on 2025-09-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_apartment_fact_price_per_m2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price_per_m2',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='fact_price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=' Цена за m²'),
        ),
    ]
