# Generated by Django 5.2.5 on 2025-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_apartment_price_per_m2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Поступило с Сделки'),
        ),
    ]
