# Generated by Django 5.2.5 on 2025-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_apartment_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='deal_Fakt_deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена Сделки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Поступило с Сделки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='remaining_deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Остаток от сделки'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='fakt_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Факт Количества'),
        ),
    ]
