# Generated by Django 5.2.5 on 2025-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_apartment_planned_deal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='fact_price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name=' Цена за m²'),
        ),
    ]
