# Generated by Django 5.2.5 on 2025-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_apartment_fact_price_per_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(max_length=20, verbose_name='Номер квартиры(обезательно)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Площадь (m²)(обезательно)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='planned_price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Планируемая цена m²(обезательно)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='Количество комнат(обезательно)'),
        ),
    ]
