# Generated by Django 5.2.5 on 2025-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_apartment_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Скидка (сом)'),
        ),
    ]
