# Generated by Django 5.2.5 on 2025-09-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_apartment_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий / Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.apartment', verbose_name='Квартира')),
            ],
        ),
    ]
