# Generated by Django 5.2.5 on 2025-11-14 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_dealpayment_created_by_dealpayment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Сдана в аренду'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание аренды'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent_price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена аренды в месяц (сом)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало аренды'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_contract',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора аренды'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Арендатор'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон арендатора'),
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('payment_date', models.DateTimeField(verbose_name='Дата платежа')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='projects.apartment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rent_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rent_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж по аренде',
                'verbose_name_plural': 'Платежи по аренде',
                'ordering': ['-payment_date'],
            },
        ),
    ]
