# Generated by Django 4.2.4 on 2026-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_apartment_is_rented_apartment_rent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_barter',
            field=models.BooleanField(default=False, verbose_name='Бартер'),
        ),
    ]
