# Generated by Django 4.2.4 on 2026-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_apartment_is_barter'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='planned_price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Плановая цена за м² по блоку'),
        ),
    ]
