# Generated by Django 5.2.5 on 2025-08-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
                ('bank_details', models.TextField(verbose_name='Банковские реквизиты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('salary', 'Зарплата'), ('advance', 'Аванс')], max_length=10, verbose_name='Тип выплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('period', models.DateField(verbose_name='За период')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
            },
        ),
    ]
