# Generated by Django 5.2.5 on 2025-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default=' ', max_length=150, verbose_name='ФИО сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_type',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('advance', 'Аванс'), ('bonus', 'Бонус'), ('premia', 'Премия')], max_length=10, verbose_name='Тип выплаты'),
        ),
    ]
