# Generated by Django 5.2.5 on 2025-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_user_employee_full_name_and_more'),
        ('projects', '0008_alter_apartment_deal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='employees', to='projects.block', verbose_name='Строительные блоки'),
        ),
    ]
