# Generated by Django 5.2.5 on 2025-09-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_blocks'),
        ('projects', '0013_alter_apartment_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blocks',
        ),
        migrations.AddField(
            model_name='employee',
            name='blocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='projects.block', verbose_name='Строительные блоки'),
        ),
    ]
