# Generated by Django 5.2.5 on 2025-08-29 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель данных')),
                ('fields', models.TextField(verbose_name='Поля для отображения')),
                ('filters', models.TextField(blank=True, verbose_name='Фильтры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('parameters', models.TextField(verbose_name='Параметры отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчета')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сохраненный отчет',
                'verbose_name_plural': 'Сохраненные отчеты',
            },
        ),
    ]
